/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tyres: Tyre;
    articles: Article;
    dealers: Dealer;
    technologies: Technology;
    'vehicle-fitments': VehicleFitment;
    'contact-submissions': ContactSubmission;
    'seasonal-content': SeasonalContent;
    'provider-settings': ProviderSetting;
    'task-routing': TaskRouting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tyres: TyresSelect<false> | TyresSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    'vehicle-fitments': VehicleFitmentsSelect<false> | VehicleFitmentsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'seasonal-content': SeasonalContentSelect<false> | SeasonalContentSelect<true>;
    'provider-settings': ProviderSettingsSelect<false> | ProviderSettingsSelect<true>;
    'task-routing': TaskRoutingSelect<false> | TaskRoutingSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'uk' | 'uk'[];
  globals: {};
  globalsSelect: {};
  locale: 'uk';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Адміністратори системи
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Зображення та файли
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Автоматично видалити білий фон (для фото шин)
   */
  removeBackground?: boolean | null;
  /**
   * Встановлюється автоматично після обробки
   */
  backgroundRemoved?: boolean | null;
  /**
   * Промпт, який використовувався для генерації (зберігається автоматично)
   */
  generationPrompt?: string | null;
  /**
   * Тип зображення для генерації промпта
   */
  generationType?: ('hero' | 'content' | 'product' | 'lifestyle') | null;
  /**
   * Сезон для hero/lifestyle зображень
   */
  generationSeason?: ('summer' | 'winter' | 'allseason') | null;
  /**
   * Розмір зображення для генерації
   */
  generationSize?: ('1024x1024' | '1792x1024' | '1024x1792') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Моделі шин Bridgestone та Firestone
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tyres".
 */
export interface Tyre {
  id: number;
  slug: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  name: string;
  brand: 'bridgestone' | 'firestone';
  season: 'summer' | 'winter' | 'allseason';
  isNew?: boolean | null;
  isPopular?: boolean | null;
  /**
   * Показувати на сайті
   */
  isPublished?: boolean | null;
  vehicleTypes: ('passenger' | 'suv' | 'van' | 'sport')[];
  image?: (number | null) | Media;
  shortDescription?: string | null;
  fullDescription?: string | null;
  euLabel?: {
    wetGrip?: ('A' | 'B' | 'C' | 'D' | 'E') | null;
    fuelEfficiency?: ('A' | 'B' | 'C' | 'D' | 'E') | null;
    noiseDb?: number | null;
    noiseClass?: ('A' | 'B' | 'C') | null;
  };
  sizes?:
    | {
        width: number;
        aspectRatio: number;
        diameter: number;
        loadIndex?: string | null;
        speedIndex?: string | null;
        id?: string | null;
      }[]
    | null;
  usage?: {
    /**
     * 0-100%
     */
    city?: number | null;
    /**
     * 0-100%
     */
    highway?: number | null;
    /**
     * 0-100%
     */
    offroad?: number | null;
    /**
     * 0-100%
     */
    winter?: number | null;
  };
  technologies?: (number | Technology)[] | null;
  /**
   * Awards from independent tests (ADAC, AutoBild, etc.)
   */
  badges?:
    | {
        type: 'winner' | 'recommended' | 'top3' | 'best_category' | 'eco';
        source: 'adac' | 'autobild' | 'tyrereviews' | 'tcs' | 'eu_label';
        year: number;
        testType?: ('summer' | 'winter' | 'allseason') | null;
        /**
         * e.g., wet_braking, snow_handling
         */
        category?: string | null;
        /**
         * Display label in Ukrainian
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  keyBenefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  testResults?:
    | {
        source?: ('adac' | 'autobild' | 'tyrereviews' | 'tcs') | null;
        testType?: ('summer' | 'winter' | 'allseason') | null;
        year?: number | null;
        testedSize?: string | null;
        position?: number | null;
        totalTested?: number | null;
        rating?: string | null;
        ratingNumeric?: number | null;
        /**
         * Link to related article
         */
        articleSlug?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Технології Bridgestone
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  slug: string;
  name: string;
  description?: string | null;
  /**
   * Icon name from Lucide icons (e.g., leaf, shield, volume-2)
   */
  icon?: string | null;
  tyres?: (number | Tyre)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Статті та поради
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  slug: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  readingTimeMinutes?: number | null;
  title: string;
  subtitle?: string | null;
  previewText: string;
  image?: (number | null) | Media;
  body?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedTyres?: (number | Tyre)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Дилери та сервісні центри
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: number;
  name: string;
  type: 'official' | 'partner' | 'service';
  city: string;
  address: string;
  latitude?: number | null;
  longitude?: number | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  /**
   * e.g., Пн-Пт: 9:00-18:00, Сб: 9:00-14:00
   */
  workingHours?: string | null;
  services?: ('tire-fitting' | 'alignment' | 'balancing' | 'storage' | 'repair')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Підбір шин по авто
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-fitments".
 */
export interface VehicleFitment {
  id: number;
  make: string;
  model: string;
  yearFrom?: number | null;
  yearTo?: number | null;
  recommendedSizes?:
    | {
        width: number;
        aspectRatio: number;
        diameter: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Звернення з форми зворотнього зв'язку
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  status?: ('new' | 'in-progress' | 'resolved') | null;
  phone: string;
  email: string;
  subject: 'tyre-selection' | 'find-dealer' | 'warranty' | 'other';
  message: string;
  /**
   * Внутрішні нотатки (не видно клієнту)
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Керування сезонним контентом на головній сторінці
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasonal-content".
 */
export interface SeasonalContent {
  id: number;
  /**
   * Наприклад: winter-2025, summer-2025
   */
  name: string;
  /**
   * Тільки один сезонний контент може бути активним
   */
  isActive?: boolean | null;
  startDate?: string | null;
  endDate?: string | null;
  featuredSeason: 'winter' | 'summer' | 'allseason';
  /**
   * Основний заголовок на головній сторінці
   */
  heroTitle: string;
  /**
   * Додатковий текст під заголовком
   */
  heroSubtitle?: string | null;
  ctaText: string;
  /**
   * Наприклад: /passenger-tyres?season=winter
   */
  ctaLink: string;
  /**
   * Tailwind CSS градієнт класи
   */
  gradient?: string | null;
  /**
   * Додатковий промо-текст для сезонної кампанії
   */
  promoText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Керування AI провайдерами. API ключі налаштовуються у файлі .env на сервері.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-settings".
 */
export interface ProviderSetting {
  id: number;
  name:
    | 'anthropic'
    | 'openai'
    | 'deepseek'
    | 'google'
    | 'groq'
    | 'openrouter'
    | 'ollama'
    | 'openai-dalle'
    | 'stability'
    | 'replicate'
    | 'leonardo';
  /**
   * Тип провайдера
   */
  type: 'llm' | 'image' | 'embedding';
  /**
   * Включити/виключити провайдера
   */
  enabled?: boolean | null;
  /**
   * Менше число = вищий пріоритет (1 = найвищий)
   */
  priority?: number | null;
  defaultModel?: string | null;
  /**
   * Список моделей для вибору
   */
  availableModels?:
    | {
        model: string;
        label?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  apiKeyEnvVar?: string | null;
  /**
   * Для провайдерів з кастомним URL
   */
  baseUrl?: string | null;
  maxTokens?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Вибір провайдера та моделі для кожного типу задачі
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-routing".
 */
export interface TaskRouting {
  id: number;
  task:
    | 'content-generation'
    | 'content-rewrite'
    | 'quick-task'
    | 'reasoning'
    | 'analysis'
    | 'content-translation'
    | 'code-generation'
    | 'image-article'
    | 'image-product'
    | 'image-lifestyle'
    | 'image-banner'
    | 'embedding-search'
    | 'embedding-similarity';
  /**
   * Для чого використовується цей тип задачі
   */
  description?: string | null;
  preferredProvider:
    | 'anthropic'
    | 'openai'
    | 'deepseek'
    | 'google'
    | 'groq'
    | 'openrouter'
    | 'ollama'
    | 'openai-dalle'
    | 'stability'
    | 'replicate'
    | 'leonardo';
  /**
   * ID моделі: claude-sonnet-4-20250514, gpt-4o, deepseek-chat, тощо
   */
  preferredModel: string;
  /**
   * Моделі для спроби якщо основна не працює (в порядку пріоритету)
   */
  fallbackModels?:
    | {
        /**
         * Наприклад: dall-e-2, gpt-4o-mini, deepseek-chat
         */
        model: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Використовуються якщо основний провайдер недоступний
   */
  fallbackProviders?:
    | ('anthropic' | 'openai' | 'deepseek' | 'google' | 'groq' | 'openrouter' | 'replicate' | 'stability')[]
    | null;
  maxRetries?: number | null;
  /**
   * Максимальний час очікування відповіді
   */
  timeoutMs?: number | null;
  /**
   * Максимальна вартість одного запиту
   */
  maxCost?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tyres';
        value: number | Tyre;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'dealers';
        value: number | Dealer;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'vehicle-fitments';
        value: number | VehicleFitment;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'seasonal-content';
        value: number | SeasonalContent;
      } | null)
    | ({
        relationTo: 'provider-settings';
        value: number | ProviderSetting;
      } | null)
    | ({
        relationTo: 'task-routing';
        value: number | TaskRouting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  removeBackground?: T;
  backgroundRemoved?: T;
  generationPrompt?: T;
  generationType?: T;
  generationSeason?: T;
  generationSize?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tyres_select".
 */
export interface TyresSelect<T extends boolean = true> {
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  name?: T;
  brand?: T;
  season?: T;
  isNew?: T;
  isPopular?: T;
  isPublished?: T;
  vehicleTypes?: T;
  image?: T;
  shortDescription?: T;
  fullDescription?: T;
  euLabel?:
    | T
    | {
        wetGrip?: T;
        fuelEfficiency?: T;
        noiseDb?: T;
        noiseClass?: T;
      };
  sizes?:
    | T
    | {
        width?: T;
        aspectRatio?: T;
        diameter?: T;
        loadIndex?: T;
        speedIndex?: T;
        id?: T;
      };
  usage?:
    | T
    | {
        city?: T;
        highway?: T;
        offroad?: T;
        winter?: T;
      };
  technologies?: T;
  badges?:
    | T
    | {
        type?: T;
        source?: T;
        year?: T;
        testType?: T;
        category?: T;
        label?: T;
        id?: T;
      };
  keyBenefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  testResults?:
    | T
    | {
        source?: T;
        testType?: T;
        year?: T;
        testedSize?: T;
        position?: T;
        totalTested?: T;
        rating?: T;
        ratingNumeric?: T;
        articleSlug?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  readingTimeMinutes?: T;
  title?: T;
  subtitle?: T;
  previewText?: T;
  image?: T;
  body?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedTyres?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  city?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  phone?: T;
  email?: T;
  website?: T;
  workingHours?: T;
  services?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  icon?: T;
  tyres?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-fitments_select".
 */
export interface VehicleFitmentsSelect<T extends boolean = true> {
  make?: T;
  model?: T;
  yearFrom?: T;
  yearTo?: T;
  recommendedSizes?:
    | T
    | {
        width?: T;
        aspectRatio?: T;
        diameter?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  phone?: T;
  email?: T;
  subject?: T;
  message?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasonal-content_select".
 */
export interface SeasonalContentSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  startDate?: T;
  endDate?: T;
  featuredSeason?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  ctaText?: T;
  ctaLink?: T;
  gradient?: T;
  promoText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-settings_select".
 */
export interface ProviderSettingsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  enabled?: T;
  priority?: T;
  defaultModel?: T;
  availableModels?:
    | T
    | {
        model?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  apiKeyEnvVar?: T;
  baseUrl?: T;
  maxTokens?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-routing_select".
 */
export interface TaskRoutingSelect<T extends boolean = true> {
  task?: T;
  description?: T;
  preferredProvider?: T;
  preferredModel?: T;
  fallbackModels?:
    | T
    | {
        model?: T;
        id?: T;
      };
  fallbackProviders?: T;
  maxRetries?: T;
  timeoutMs?: T;
  maxCost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}